version: '3'

services:
  flask:
    container_name: local_flask
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    env_file:
      - .env
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
      - "--port=5000"
      - "--reload"
      - "--debug"
    depends_on:
      - mysql

  mysql:
    container_name: local_mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env