version: '3'

volumes:
  db_data: {}

services:
  flask:
    container_name: local_flask
    build:
      context: .
      dockerfile: docker/Dockerfile-flask
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
      - "--port=5000"
      - "--reload"
      - "--debug"
    depends_on:
      - mysql

  mysql:
    container_name: local_mysql
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - .env